# -*- coding: utf-8 -*-
"""Projeto pessoal - Campeonato europeu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERyuOSocmRVvo4c0z8a-KkpCbZmt_AoO

<h2 style="color: #66E0EF;">🚀 Passo Único: Extração e Consolidação de Dados (2022 a 2025)</h2>
Nesta etapa definitiva, aplicamos o conceito de <b>Single Source of Truth</b> (Fonte Única da Verdade). Utilizamos a API do portal <b>football-data.org</b> para extrair simultaneamente o histórico recente e a temporada em andamento (24/25) das 5 grandes ligas europeias. Isso garante a padronização automática dos nomes dos times e dos IDs das ligas, eliminando a necessidade de tratamentos complexos de dados (ETL) e gerando nossa Base Mestre final em um único processo eficiente.
"""

import requests
import pandas as pd
import time

print("Iniciando a extração unificada (2022 a 2024/25) via football-data.org...")

# 1. CHAVE DO FOOTBALL-DATA AQUI
api_token = "77dcc6b6e83749d3bec7dbf005657c1d"

headers = {
    'X-Auth-Token': api_token
}

# As siglas do "Big 6"
ligas_siglas = ['PL', 'PD', 'SA', 'BL1', 'FL1', 'PPL']
temporadas = [2024, 2025] # 2024 (Temporada passada) e 2025 (Temporada atual 25/26)

dados_unificados = []

for sigla in ligas_siglas:
    for ano in temporadas:
        url = f"http://api.football-data.org/v4/competitions/{sigla}/standings?season={ano}"

        response = requests.get(url, headers=headers)

        if response.status_code == 200:
            dados = response.json()
            nome_liga = dados['competition']['name']

            # Pegando apenas a tabela de classificação geral (TOTAL)
            try:
                tabela = dados['standings'][0]['table']
                print(f"Sucesso: {nome_liga} - Temporada {ano}/{ano+1}")

                for posicao in tabela:
                    # Garantindo que a forma recente venha sem vírgulas
                    forma = str(posicao.get('form', '')).replace(',', '')

                    dados_unificados.append({
                        'Liga_ID': sigla,
                        'Liga_Nome': nome_liga,
                        'Temporada': ano + 1, # Somando 1 para ficar "2023, 2024, 2025" e bater com seus visuais
                        'Posicao': posicao['position'],
                        'Time': posicao['team']['name'],
                        'Pontos': posicao['points'],
                        'Jogos': posicao['playedGames'],
                        'Vitorias': posicao['won'],
                        'Empates': posicao['draw'],
                        'Derrotas': posicao['lost'],
                        'Gols_Pro': posicao['goalsFor'],
                        'Gols_Contra': posicao['goalsAgainst'],
                        'Saldo_Gols': posicao['goalDifference'],
                        'Forma_Recente': forma
                    })
            except (KeyError, IndexError):
                print(f"Aviso: Dados de classificação não encontrados para {sigla} em {ano}.")
        else:
            print(f"Erro na liga {sigla} ({ano}): {response.status_code} - {response.text}")

        # Pausa de 7 segundos para respeitar o limite de 10 requisições/minuto do plano gratuito
        time.sleep(7)

# Gerando a base mestre unificada
df_final = pd.DataFrame(dados_unificados)

print(f"\nExtração Concluída! Nossa base Mestre tem {df_final.shape[0]} linhas perfeitas e padronizadas.")

# Salvando
nome_arquivo_final = 'base_mestre_futebol_europeu.csv'
df_final.to_csv(nome_arquivo_final, index=False)
